apps:
  -
    script: 'bin/select'
    name: 'select'
    instances: 2
    exec_mode: cluster
    max_memory_restart: 500M
    restart_delay: 5000
    kill_timeout: 10000
    listen_timeout: 10000
    wait_ready: true
    # watch: config/*.yml